[package]
name = "sdme-drop-privs-gen"
version = "0.1.0"
edition = "2021"
description = "Generates tiny static ELF binaries for privilege dropping in chrooted systemd units"
publish = false

[[bin]]
name = "sdme-drop-privs-gen"
path = "src/main.rs"
